---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: diskencrypt=false release=prod ubuntuversion=focal arch=amd64 username=sys-admin password=P@ssw0rd! epassword=\$6\$Q5mP.pqw5ydDHHGN\$gxx1nGbwCWpyGeO93EnNNr9BqZ9PtwIiuvWoGniU7qq8wG2yfa33xBbmTcKjgZ65XmPno7S4.SOP7XCwOR0gw0
